controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_booking_submit:
    path: /reservation/submit
    controller: App\Controller\BookingController::submit
    methods: [POST]

check_reservation:
    path: /reservation/check-reservation
    controller: App\Controller\BookingController::checkReservation
    methods: [GET]
